#!/usr/bin/env bash
# Sourced, not executed. Concatenates policies/recipes/<name>.allowlist fragments into one
# generated file and exports AGENT_LAB_EGRESS_ALLOWLIST pointing at it. Compose already
# mounts ${AGENT_LAB_EGRESS_ALLOWLIST} into Squid, so no squid.conf change is needed.
#
# Compose precedence note: a shell-exported variable overrides the same key from
# --env-file, so this generated path wins over any value in .env.local. Do NOT hard-set
# AGENT_LAB_EGRESS_ALLOWLIST in .env.local when using recipes.
#
# Squid semantics that guarantee a generated file can't weaken the boundary:
#   - dstdomain is an OR-set, so concat order is irrelevant to matching.
#   - private-range / raw-IP / unsafe-port denies run BEFORE the allow rule.

agent_lab_sha256_file() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | awk '{print $1}'
  elif command -v shasum >/dev/null 2>&1; then
    shasum -a 256 "$1" | awk '{print $1}'
  else
    printf 'FAIL SHA-256 tool required (sha256sum or shasum)\n' >&2
    return 1
  fi
}

agent_lab_build_allowlist() {
  local recipes recipes_spaced out_dir out tmp hash r frag
  recipes="${AGENT_LAB_ALLOWLIST_RECIPES:-base}"
  out_dir="${REPO_ROOT:?REPO_ROOT not set}/.cache/squid"
  mkdir -p "$out_dir"
  tmp="$(mktemp "${out_dir}/allowlist.XXXXXX")"
  { printf '# Generated by scripts/lib/allowlist.sh -- do not edit by hand.\n'
    printf '# Composed from recipes: %s\n' "$recipes"; } > "$tmp"
  recipes_spaced="$(printf '%s' "$recipes" | tr ',' ' ')"
  set -f
  # shellcheck disable=SC2086  # intentional word-splitting of the recipe list (globbing disabled by `set -f`)
  for r in $recipes_spaced; do
    [ -n "$r" ] || continue
    frag="${REPO_ROOT}/policies/recipes/${r}.allowlist"
    if [ ! -f "$frag" ]; then
      set +f
      rm -f "$tmp"
      printf 'FAIL unknown allowlist recipe: %s (%s)\n' "$r" "$frag" >&2
      return 1
    fi
    { printf '\n# --- recipe: %s ---\n' "$r"; grep -vE '^[[:space:]]*(#|$)' "$frag" || true; } >> "$tmp"
  done
  set +f

  if ! hash="$(agent_lab_sha256_file "$tmp")"; then
    rm -f "$tmp"
    return 1
  fi
  out="${out_dir}/allowlist.${hash}.txt"
  if [ -f "$out" ]; then
    rm -f "$tmp"
  else
    mv "$tmp" "$out"
  fi
  printf 'PASS generated allowlist [%s] sha256=%s -> %s\n' "$recipes" "$hash" "$out"
  export AGENT_LAB_EGRESS_ALLOWLIST="$out"
  export AGENT_LAB_EGRESS_POLICY_SHA256="$hash"
}
