#!/usr/bin/env bash
# tools/render-adapters.sh — generate the per-tool rule bodies from shared policy, so the
# three adapters are never hand-maintained. Single policy source:
#   - policy/allow.commands   -> the auto-approve allow set (translated per tool)
#   - tools/pretooluse-guard.sh -> the live command decision point. Command denials are not copied
#                                  into client startup configuration, where they can outlive the
#                                  checkout that defined them.
#
# Generated files (do not hand-edit the marked/whole regions):
#   .claude/settings.json          (whole file — strict JSON, no comments)
#   .codex/rules/agent-lab.rules   (whole file — execpolicy prefix_rule; token-based)
#   .grok/config.toml              (whole file — [permission] + project MCP)
#
# Codex notes: execpolicy is TOKEN-prefix, so branch-aware decisions cannot be expressed as rules;
# the live guard enforces command policy while native rules only auto-approve known-safe prefixes.
#
# Idempotent. Run as a maintenance task:  AGENT_LAB_MAINTENANCE=1 tools/render-adapters.sh
set -euo pipefail
root="$(cd "$(dirname "$(readlink -f "$0")")/.." && pwd)"
cd "$root"
command -v jq >/dev/null 2>&1 || { echo "render-adapters: jq is required" >&2; exit 1; }

mapfile -t ALLOW < <(grep -vE '^[[:space:]]*(#|$)' policy/allow.commands)

# Client hook names differ even though all three clients invoke the same Serena tools.
SERENA_MCP_MUTATORS='mcp__serena__replace_symbol_body|mcp__serena__insert_before_symbol|mcp__serena__insert_after_symbol'

toks() { # "git commit" -> "git", "commit"
  printf '%s' "$1" | awk '{for(i=1;i<=NF;i++) printf "%s\"%s\"",(i>1?", ":""),$i}'
}

# ---------------- Claude: whole settings.json via jq (guarantees valid JSON) ----------------
emit_claude() {
  local allow=() deny=() c
  for c in "${ALLOW[@]}"; do allow+=("Bash(${c}:*)"); done
  # Current Claude Code applies Edit(path) permission rules to every file-editing tool, including
  # Write. Emitting Write(path) rules is ignored and produces startup warnings.
  allow+=("Read(**)" "Edit(**)")
  # NOTE: protected-path Edit/Write denies are intentionally NOT emitted for Claude. Claude's native
  # permissions.deny has NO maintenance bypass, so a native Edit(rail) deny self-locks even sanctioned
  # maintenance (the §13.9 self-lock; see docs/agent-config.md). The guard's Edit|Write matcher
  # enforces rail read-only WITH the AGENT_LAB_MAINTENANCE bypass. Command policy also stays in that
  # live guard so client startup state cannot retain obsolete command denials. Common local env/key
  # paths stay natively denied; the guard covers other .env variants while permitting the tracked
  # .env.example documentation.
  deny+=(
    "Read(**/.env)" "Read(**/.env.local)" "Read(**/.env.*.local)" "Read(**/secrets/**)" "Read(**/*.pem)" "Read(**/*.key)" "Read(**/*.kdbx)"
    "Edit(**/.env)" "Edit(**/.env.local)" "Edit(**/.env.*.local)" "Edit(**/secrets/**)" "Edit(**/*.pem)" "Edit(**/*.key)" "Edit(**/*.kdbx)"
  )

  local guard='bash "$(git rev-parse --show-toplevel)/tools/pretooluse-guard.sh"'
  local boot='bash "$(git rev-parse --show-toplevel)/tools/session-bootstrap.sh" claude'
  local file_matcher="Read|Edit|Write|MultiEdit|NotebookEdit|${SERENA_MCP_MUTATORS}"
  mkdir -p .claude
  jq -n \
    --argjson allow "$(printf '%s\n' "${allow[@]}" | jq -R . | jq -s .)" \
    --argjson deny "$(printf '%s\n' "${deny[@]}" | jq -R . | jq -s .)" \
    --arg guard "$guard" --arg boot "$boot" --arg file_matcher "$file_matcher" \
    '{
      "$schema": "https://json.schemastore.org/claude-code-settings.json",
      permissions: { defaultMode: "acceptEdits", allow: $allow, deny: $deny },
      hooks: {
        PreToolUse: [
          { matcher: "Bash", hooks: [ { type: "command", command: $guard } ] },
          { matcher: $file_matcher, hooks: [ { type: "command", command: $guard } ] }
        ],
        SessionStart: [
          { matcher: "startup|resume", hooks: [ { type: "command", command: $boot } ] }
        ]
      }
    }' > .claude/settings.json
}

# ---------------- Codex: execpolicy rules (token-based) ----------------
emit_codex() {
  local c
  mkdir -p .codex/rules
  {
    echo "# >>> GENERATED by tools/render-adapters.sh — DO NOT EDIT (edit policy/* and re-run) >>>"
    echo "# Codex execpolicy: auto-approve the scoped AGENTS.md workflow. The live PreToolUse guard"
    echo "# (tools/pretooluse-guard.sh) decides command policy from the current checkout."
    echo "# Command denials are intentionally absent here so startup-cached rules cannot become stale."
    echo
    echo "# -- allow: local git (clean token prefixes only; workspace-write auto-runs the rest) --"
    for c in "${ALLOW[@]}"; do
      case "$c" in
        git\ *) printf 'prefix_rule(pattern = [%s], decision = "allow", justification = "agent-lab local-git set")\n' "$(toks "$c")" ;;
        gh\ *) printf 'prefix_rule(pattern = [%s], decision = "allow", justification = "agent-lab scoped GitHub workflow")\n' "$(toks "$c")" ;;
        shellcheck) printf 'prefix_rule(pattern = ["shellcheck"], decision = "allow", justification = "agent-lab lint")\n' ;;
      esac
    done
    echo "# <<< END GENERATED <<<"
  } > .codex/rules/agent-lab.rules
}

# ---------------- Grok: whole config.toml ([permission] + project MCP) ----------------
emit_grok() {
  local c
  mkdir -p .grok
  {
    echo "# >>> GENERATED by tools/render-adapters.sh — DO NOT EDIT (edit policy/* and re-run) >>>"
    echo "# Grok Build project config. The live PreToolUse guard (tools/pretooluse-guard.sh) decides"
    echo "# command policy from the current checkout. Hooks are wired in .grok/hooks/."
    echo
    echo "# Autonomy posture is set by the OPERATOR at launch — NOT here. Grok treats [ui] permission_mode"
    echo "# as a global/user default that can leak across projects, and 'always-approve' is a launch FLAG,"
    echo "# not a config enum (valid config enum: default|acceptEdits|auto|dontAsk|bypassPermissions|plan)."
    echo "# Launch:  grok --always-approve   — the live PreToolUse hook still evaluates commands before"
    echo "# execution. Static deny entries below are limited to secret-shaped file paths."
    echo
    echo "[permission]"
    echo "deny = ["
    echo '  "Read(**/.env)", "Read(**/.env.local)", "Read(**/.env.*.local)", "Read(**/secrets/**)", "Read(**/*.pem)", "Read(**/*.key)", "Read(**/*.kdbx)",'
    echo '  "Edit(**/.env)", "Edit(**/.env.local)", "Edit(**/.env.*.local)", "Edit(**/secrets/**)", "Edit(**/*.pem)", "Edit(**/*.key)", "Edit(**/*.kdbx)",'
    echo '  "Write(**/.env)", "Write(**/.env.local)", "Write(**/.env.*.local)", "Write(**/secrets/**)", "Write(**/*.pem)", "Write(**/*.key)", "Write(**/*.kdbx)",'
    echo ']'
    echo "allow = ["
    for c in "${ALLOW[@]}"; do printf '  "Bash(%s*)",\n' "$c"; done
    echo '  "Read(**)", "Edit(**)", "Write(**)",'
    echo ']'
    echo "# <<< END GENERATED <<<"
    echo
    echo "# Serena is project-scoped and starts in a dedicated no-network container."
    echo "# Do not pass --project here: explicit activation must remain recoverable."
    echo "[mcp_servers.serena]"
    echo 'command = "env"'
    echo 'args = ["-u", "BASH_ENV", "-u", "ENV", "bash", "--noprofile", "--norc", "-c", "root=\"$(git rev-parse --show-toplevel)\" && exec \"$root/scripts/serena-mcp\" --context=grok"]'
  } > .grok/config.toml
}

emit_claude
emit_codex
emit_grok
echo "render-adapters: wrote .claude/settings.json .codex/rules/agent-lab.rules .grok/config.toml"
